// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_2rmCQA_eyiw6p_H2rbzUEoGovDOkK2Q',
    appId: '1:550117626799:android:94e5a0768253a1f264d55a',
    messagingSenderId: '550117626799',
    projectId: 'zoe-app-6e634',
    storageBucket: 'zoe-app-6e634.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSaOiyZrWgBrWpwyXiUECgZu1nynyR0Sk',
    appId: '1:550117626799:ios:d697fe2acf10d62164d55a',
    messagingSenderId: '550117626799',
    projectId: 'zoe-app-6e634',
    storageBucket: 'zoe-app-6e634.firebasestorage.app',
    androidClientId: '550117626799-uav6v1lntqcmlaetqqdrh54jv3fufqvf.apps.googleusercontent.com',
    iosClientId: '550117626799-g97cn5okmmasqh2130muvif49rdg226a.apps.googleusercontent.com',
    iosBundleId: 'io.riversea.zoeapp',
  );
}
